### ISSUE TITLE
Example bug

### ISSUE THREAD

**Issue by kohalmykristof** [EDMdesigner/knobjs#26]
Knob example throws error at knob-items-per-page component.
knockout-min.js:16 Uncaught TypeError: config.itemsPerPage is not a function.
Maybe caused by " #10 - list component should save its state" task with in-progress status.

**Comment by kohalmykristof** [comment]
Oneo of possible reasons of problem depends on https://github.com/EDMdesigner/knobjs/issues/10

**Comment by balintsoos** [comment]
fixed in issue #10
